services:
  - type: web
    name: college-album-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: college-album-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.9.18

databases:
  - name: college-album-db
    databaseName: collegealbum
    user: collegealbum 